### ISSUE TITLE
Importing Issues

### ISSUE THREAD

**Issue by CanadianEngineer** [tiagorg/jasmine-precondition#2]
Hey, I don't really know the best way to get in contact with you regarding this issue, other than making a github issue.

I've installed your preCondition function and I'm trying to run it, however, I'm getting the error "preCondition is undefined". I was wondering how would you go about including your function in an Angular2 Project through npm?

**Comment by tiagorg** [comment]
Hi @CanadianEngineer, how are you running Jasmine? is it through Karma?

Depending on you run your Jasmine tests, you would either require in your module:
```var preCondition = require('jasmine-precondition');```

Or you can also manually include the file `lib/jasmine-precondition.js` in the jasmine path (which may live in your Karma config should you use Karma), before your tests.

**Comment by CanadianEngineer** [comment]
Yeah, I'm running Jasmine through Karma.

I could have sworn I tried `var preCondition = require('jasmine-precondition');`, but I guess not. It works now, thanks!

**Comment by tiagorg** [comment]
cool! glad to know
